package com.jasper.invoice.domain.validation;

public enum ValidationIssueCode {
    SUBTOTAL_MISMATCH,
    TOTAL_MISMATCH,
    MISSING_INVOICE_NUMBER,
    MISSING_INVOICE_DATE,
    MISSING_SUPPLIER,
    MISSING_CUSTOMER,
    MISSING_LINE_ITEMS,
    MISSING_TOTAL,
    MISSING_LINE_ITEM_DESCRIPTION,
    MISSING_LINE_ITEM_QUANTITY,
    MISSING_LINE_ITEM_UNIT_PRICE
}